#pragma once

// ############# Configuration parsing options #############

#define CONFIGURATION_GROUP_SETTINGS_NAME "settings"
#define CONFIGURATION_GROUP_VERSIONS_NAME "versions"
#define CONFIGURATION_GROUP_MATCHING_NAME "matching"

#define CONFIGURATION_FIELD_LAZY_LOADING_NAME "lazy"
#define CONFIGURATION_FIELD_LAZY_LOADING_DEFAULT true

#define CONFIGURATION_FIELD_MATCHING_PRIORITY_NAME "priority"
#define CONFIGURATION_FIELD_MATCHING_REGEX_NAME "regex"