#pragma once

// Std
#include <memory>
// OpenSSL
#include <openssl/evp.h>
// Project
#include "robo_trace/processing/stage/stage.hpp"
#include "robo_trace_openssl_plugin/key_manager.hpp"
#include "robo_trace_openssl_plugin/chain/configuration.hpp"


namespace robo_trace {

/**
 * Implements a hash chaining stage based on the SHA256 algorithm.
 * The hash for some message is generated by piping the concatenation
 * of the previouses message hash with the current message into the
 * hashing algorithm. 
 * 
 * This is stage must be executed in a blocking fashion! Only one 
 */
class OpenSSLHashChainForwardStage final : public ProcessingStage {

public:

    /**
     * TODO
     */
    OpenSSLHashChainForwardStage(const OpenSSLHashChainConfiguration::Ptr& configuration, const OpenSSLPluginKeyManager::Ptr& key_manager, const DataContainer::Ptr& metadata);

    /**
     * TODO
     */
    virtual ~OpenSSLHashChainForwardStage();

    /**
     *
     */
    virtual ProcessingMode getMode() const final override;
  
    /**
     * TODO
     */
    virtual void process(const ProcessingContext::Ptr& context) final override;

private:

    /** */
    const OpenSSLHashChainConfiguration::Ptr m_configuration;

    /** */
    const EVP_MD* m_hashing_method;
    /** */
    EVP_MD_CTX* m_hashing_context;
    
    /** */
    unsigned char m_hash_buffer[EVP_MAX_MD_SIZE];
    /** */
    unsigned int m_hash_buffer_length = 0;

};

} 